fix vim syntastic: --parse-only => -Z parse-only
when saving .rs files under vim
do not fail to run the syntax checker
error: Unrecognized option: 'parse-only'.

due to this commit
953f294ea30253bb5578e3c895d17fcc97c20dce
which removed the deprecated flag --parse-only